/* data-reading.js — daily reading passages, parsed word by word.
   Each word: [surface, gloss, parse, lexical form]
   Greek text follows public-domain critical editions of the Greek NT and LXX.
   English renderings are deliberately wooden — they show you the Greek, not
   good English. */
var GK = window.GK || {}; window.GK = GK;

GK.passages = [
  {
    id: 'jn1-1', ref: 'John 1:1', level: 1, title: 'In the beginning was the Word',
    en: 'In the beginning was the Word, and the Word was with God, and the Word was God.',
    words: [
      ['Ἐν', 'in', 'prep +dat', 'ἐν'],
      ['ἀρχῇ', 'beginning', 'dat sg fem', 'ἀρχή, -ῆς, ἡ'],
      ['ἦν', 'was', 'impf act ind 3sg', 'εἰμί'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['λόγος,', 'word', 'nom sg masc', 'λόγος, -ου, ὁ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['λόγος', 'word', 'nom sg masc', 'λόγος, -ου, ὁ'],
      ['ἦν', 'was', 'impf act ind 3sg', 'εἰμί'],
      ['πρὸς', 'with, toward', 'prep +acc', 'πρός'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['θεόν,', 'God', 'acc sg masc', 'θεός, -οῦ, ὁ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['θεὸς', 'God', 'nom sg masc', 'θεός, -οῦ, ὁ'],
      ['ἦν', 'was', 'impf act ind 3sg', 'εἰμί'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['λόγος.', 'word', 'nom sg masc', 'λόγος, -ου, ὁ']
    ],
    note: 'θεὸς has no article and stands first for emphasis — the Word shares the nature of God, without being identified as the same person as ὁ θεόν just named.'
  },
  {
    id: 'jn1-2', ref: 'John 1:2–3', level: 2, title: 'All things through him',
    en: 'This one was in the beginning with God. All things came into being through him, and apart from him not one thing came into being that has come into being.',
    words: [
      ['οὗτος', 'this one', 'nom sg masc', 'οὗτος'],
      ['ἦν', 'was', 'impf act ind 3sg', 'εἰμί'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['ἀρχῇ', 'beginning', 'dat sg fem', 'ἀρχή, -ῆς, ἡ'],
      ['πρὸς', 'with', 'prep +acc', 'πρός'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['θεόν.', 'God', 'acc sg masc', 'θεός, -οῦ, ὁ'],
      ['πάντα', 'all things', 'nom pl neut', 'πᾶς, πᾶσα, πᾶν'],
      ["δι'", 'through', 'prep +gen', 'διά'],
      ['αὐτοῦ', 'him', 'gen sg masc', 'αὐτός'],
      ['ἐγένετο,', 'came into being', 'aor mid ind 3sg', 'γίνομαι'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['χωρὶς', 'apart from', 'prep +gen', 'χωρίς'],
      ['αὐτοῦ', 'him', 'gen sg masc', 'αὐτός'],
      ['ἐγένετο', 'came into being', 'aor mid ind 3sg', 'γίνομαι'],
      ['οὐδὲ', 'not even', 'conj', 'οὐδέ'],
      ['ἕν', 'one thing', 'nom sg neut', 'εἷς, μία, ἕν'],
      ['ὃ', 'which', 'nom sg neut', 'ὅς, ἥ, ὅ'],
      ['γέγονεν.', 'has come into being', 'perf act ind 3sg', 'γίνομαι']
    ],
    note: 'ἐγένετο is aorist (a completed act); γέγονεν is perfect (a past act with standing results). The tense change is the whole point of the sentence.'
  },
  {
    id: 'jn1-4', ref: 'John 1:4–5', level: 2, title: 'The light shines in the darkness',
    en: 'In him was life, and the life was the light of men; and the light shines in the darkness, and the darkness did not overcome it.',
    words: [
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['αὐτῷ', 'him', 'dat sg masc', 'αὐτός'],
      ['ζωὴ', 'life', 'nom sg fem', 'ζωή, -ῆς, ἡ'],
      ['ἦν,', 'was', 'impf act ind 3sg', 'εἰμί'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['ζωὴ', 'life', 'nom sg fem', 'ζωή, -ῆς, ἡ'],
      ['ἦν', 'was', 'impf act ind 3sg', 'εἰμί'],
      ['τὸ', 'the', 'nom sg neut', 'ὁ'],
      ['φῶς', 'light', 'nom sg neut', 'φῶς, φωτός, τό'],
      ['τῶν', 'of the', 'gen pl masc', 'ὁ'],
      ['ἀνθρώπων·', 'of men', 'gen pl masc', 'ἄνθρωπος, -ου, ὁ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['τὸ', 'the', 'nom sg neut', 'ὁ'],
      ['φῶς', 'light', 'nom sg neut', 'φῶς, φωτός, τό'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['τῇ', 'the', 'dat sg fem', 'ὁ'],
      ['σκοτίᾳ', 'darkness', 'dat sg fem', 'σκοτία, -ας, ἡ'],
      ['φαίνει,', 'shines', 'pres act ind 3sg', 'φαίνω'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['σκοτία', 'darkness', 'nom sg fem', 'σκοτία, -ας, ἡ'],
      ['αὐτὸ', 'it', 'acc sg neut', 'αὐτός'],
      ['οὐ', 'not', 'adv', 'οὐ'],
      ['κατέλαβεν.', 'overcame, grasped', 'aor act ind 3sg', 'καταλαμβάνω']
    ],
    note: 'αὐτὸ is neuter because it points back to τὸ φῶς. Greek pronouns agree in gender with what they refer to, not with English sense.'
  },
  {
    id: 'jn1-14', ref: 'John 1:14', level: 3, title: 'The Word became flesh',
    en: 'And the Word became flesh and dwelt among us, and we beheld his glory, glory as of an only son from a father, full of grace and truth.',
    words: [
      ['Καὶ', 'and', 'conj', 'καί'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['λόγος', 'word', 'nom sg masc', 'λόγος, -ου, ὁ'],
      ['σὰρξ', 'flesh', 'nom sg fem', 'σάρξ, σαρκός, ἡ'],
      ['ἐγένετο', 'became', 'aor mid ind 3sg', 'γίνομαι'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἐσκήνωσεν', 'dwelt, pitched his tent', 'aor act ind 3sg', 'σκηνόω'],
      ['ἐν', 'among', 'prep +dat', 'ἐν'],
      ['ἡμῖν,', 'us', 'dat pl', 'ἐγώ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἐθεασάμεθα', 'we beheld', 'aor mid ind 1pl', 'θεάομαι'],
      ['τὴν', 'the', 'acc sg fem', 'ὁ'],
      ['δόξαν', 'glory', 'acc sg fem', 'δόξα, -ης, ἡ'],
      ['αὐτοῦ,', 'of him', 'gen sg masc', 'αὐτός'],
      ['δόξαν', 'glory', 'acc sg fem', 'δόξα, -ης, ἡ'],
      ['ὡς', 'as', 'conj', 'ὡς'],
      ['μονογενοῦς', 'of an only one', 'gen sg masc', 'μονογενής, -ές'],
      ['παρὰ', 'from', 'prep +gen', 'παρά'],
      ['πατρός,', 'a father', 'gen sg masc', 'πατήρ, πατρός, ὁ'],
      ['πλήρης', 'full', 'nom sg masc', 'πλήρης, -ες'],
      ['χάριτος', 'of grace', 'gen sg fem', 'χάρις, -ιτος, ἡ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἀληθείας.', 'of truth', 'gen sg fem', 'ἀλήθεια, -ας, ἡ']
    ],
    note: 'χάριτος and ἀληθείας are genitive because πλήρης ("full") takes a genitive of content — full *of* something.'
  },
  {
    id: 'jn3-16', ref: 'John 3:16', level: 2, title: 'For God so loved',
    en: 'For in this way God loved the world, so that he gave the only Son, in order that everyone believing in him might not perish but have eternal life.',
    words: [
      ['Οὕτως', 'in this way', 'adv', 'οὕτως'],
      ['γὰρ', 'for', 'conj', 'γάρ'],
      ['ἠγάπησεν', 'loved', 'aor act ind 3sg', 'ἀγαπάω'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['θεὸς', 'God', 'nom sg masc', 'θεός, -οῦ, ὁ'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['κόσμον,', 'world', 'acc sg masc', 'κόσμος, -ου, ὁ'],
      ['ὥστε', 'so that', 'conj', 'ὥστε'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['υἱὸν', 'son', 'acc sg masc', 'υἱός, -οῦ, ὁ'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['μονογενῆ', 'only, one of a kind', 'acc sg masc', 'μονογενής, -ές'],
      ['ἔδωκεν,', 'he gave', 'aor act ind 3sg', 'δίδωμι'],
      ['ἵνα', 'in order that', 'conj', 'ἵνα'],
      ['πᾶς', 'everyone', 'nom sg masc', 'πᾶς, πᾶσα, πᾶν'],
      ['ὁ', 'the one', 'nom sg masc', 'ὁ'],
      ['πιστεύων', 'believing', 'pres act ptc nom sg masc', 'πιστεύω'],
      ['εἰς', 'in, into', 'prep +acc', 'εἰς'],
      ['αὐτὸν', 'him', 'acc sg masc', 'αὐτός'],
      ['μὴ', 'not', 'particle', 'μή'],
      ['ἀπόληται', 'should perish', 'aor mid subj 3sg', 'ἀπόλλυμι'],
      ["ἀλλ'", 'but', 'conj', 'ἀλλά'],
      ['ἔχῃ', 'should have', 'pres act subj 3sg', 'ἔχω'],
      ['ζωὴν', 'life', 'acc sg fem', 'ζωή, -ῆς, ἡ'],
      ['αἰώνιον.', 'eternal', 'acc sg fem', 'αἰώνιος, -ον']
    ],
    note: 'Οὕτως is "in this way", not "so much". And ἵνα pulls both verbs into the subjunctive — that is why they are ἀπόληται and ἔχῃ rather than ἀπώλετο and ἔχει.'
  },
  {
    id: 'mk1-1', ref: 'Mark 1:1', level: 1, title: 'The beginning of the gospel',
    en: 'The beginning of the gospel of Jesus Christ, Son of God.',
    words: [
      ['Ἀρχὴ', 'beginning', 'nom sg fem', 'ἀρχή, -ῆς, ἡ'],
      ['τοῦ', 'of the', 'gen sg neut', 'ὁ'],
      ['εὐαγγελίου', 'gospel', 'gen sg neut', 'εὐαγγέλιον, -ου, τό'],
      ['Ἰησοῦ', 'of Jesus', 'gen sg masc', 'Ἰησοῦς, -οῦ, ὁ'],
      ['Χριστοῦ', 'of Christ', 'gen sg masc', 'Χριστός, -οῦ, ὁ'],
      ['υἱοῦ', 'son', 'gen sg masc', 'υἱός, -οῦ, ὁ'],
      ['θεοῦ.', 'of God', 'gen sg masc', 'θεός, -οῦ, ὁ']
    ],
    note: 'Five genitives in a row, and no verb anywhere. A good place to practise asking what each genitive is doing.'
  },
  {
    id: 'mt5-3', ref: 'Matthew 5:3–4', level: 2, title: 'Blessed are the poor',
    en: 'Blessed are the poor in spirit, because theirs is the kingdom of the heavens. Blessed are those who mourn, because they will be comforted.',
    words: [
      ['Μακάριοι', 'blessed', 'nom pl masc', 'μακάριος, -ία, -ον'],
      ['οἱ', 'the', 'nom pl masc', 'ὁ'],
      ['πτωχοὶ', 'poor', 'nom pl masc', 'πτωχός, -ή, -όν'],
      ['τῷ', 'in the', 'dat sg neut', 'ὁ'],
      ['πνεύματι,', 'spirit', 'dat sg neut', 'πνεῦμα, -ατος, τό'],
      ['ὅτι', 'because', 'conj', 'ὅτι'],
      ['αὐτῶν', 'of them', 'gen pl masc', 'αὐτός'],
      ['ἐστιν', 'is', 'pres act ind 3sg', 'εἰμί'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['βασιλεία', 'kingdom', 'nom sg fem', 'βασιλεία, -ας, ἡ'],
      ['τῶν', 'of the', 'gen pl masc', 'ὁ'],
      ['οὐρανῶν.', 'heavens', 'gen pl masc', 'οὐρανός, -οῦ, ὁ'],
      ['μακάριοι', 'blessed', 'nom pl masc', 'μακάριος, -ία, -ον'],
      ['οἱ', 'the ones', 'nom pl masc', 'ὁ'],
      ['πενθοῦντες,', 'mourning', 'pres act ptc nom pl masc', 'πενθέω'],
      ['ὅτι', 'because', 'conj', 'ὅτι'],
      ['αὐτοὶ', 'they themselves', 'nom pl masc', 'αὐτός'],
      ['παρακληθήσονται.', 'will be comforted', 'fut pass ind 3pl', 'παρακαλέω']
    ],
    note: 'Μακάριοι is a predicate adjective with εἰμί left unwritten — Greek is happy to omit "are".'
  },
  {
    id: 'mt6-9', ref: 'Matthew 6:9–10', level: 2, title: 'Our Father',
    en: 'Our Father who is in the heavens, let your name be treated as holy; let your kingdom come; let your will be done, as in heaven so also on earth.',
    words: [
      ['Πάτερ', 'Father', 'voc sg masc', 'πατήρ, πατρός, ὁ'],
      ['ἡμῶν', 'our', 'gen pl', 'ἐγώ'],
      ['ὁ', 'the one', 'nom sg masc', 'ὁ'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['τοῖς', 'the', 'dat pl masc', 'ὁ'],
      ['οὐρανοῖς·', 'heavens', 'dat pl masc', 'οὐρανός, -οῦ, ὁ'],
      ['ἁγιασθήτω', 'let it be made holy', 'aor pass impv 3sg', 'ἁγιάζω'],
      ['τὸ', 'the', 'nom sg neut', 'ὁ'],
      ['ὄνομά', 'name', 'nom sg neut', 'ὄνομα, -ατος, τό'],
      ['σου·', 'your', 'gen sg', 'σύ'],
      ['ἐλθέτω', 'let it come', 'aor act impv 3sg', 'ἔρχομαι'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['βασιλεία', 'kingdom', 'nom sg fem', 'βασιλεία, -ας, ἡ'],
      ['σου·', 'your', 'gen sg', 'σύ'],
      ['γενηθήτω', 'let it come to pass', 'aor pass impv 3sg', 'γίνομαι'],
      ['τὸ', 'the', 'nom sg neut', 'ὁ'],
      ['θέλημά', 'will', 'nom sg neut', 'θέλημα, -ατος, τό'],
      ['σου,', 'your', 'gen sg', 'σύ'],
      ['ὡς', 'as', 'conj', 'ὡς'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['οὐρανῷ', 'heaven', 'dat sg masc', 'οὐρανός, -οῦ, ὁ'],
      ['καὶ', 'also', 'conj', 'καί'],
      ['ἐπὶ', 'on', 'prep +gen', 'ἐπί'],
      ['γῆς.', 'earth', 'gen sg fem', 'γῆ, γῆς, ἡ']
    ],
    note: 'Three third-person imperatives in a row. English has no clean equivalent, so we reach for "let ...".'
  },
  {
    id: 'mt6-11', ref: 'Matthew 6:11–13', level: 3, title: 'Give us today',
    en: 'Give us today our daily bread; and forgive us our debts, as we also have forgiven our debtors; and do not bring us into testing, but rescue us from the evil one.',
    words: [
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['ἄρτον', 'bread', 'acc sg masc', 'ἄρτος, -ου, ὁ'],
      ['ἡμῶν', 'our', 'gen pl', 'ἐγώ'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['ἐπιούσιον', 'daily, for the coming day', 'acc sg masc', 'ἐπιούσιος, -ον'],
      ['δὸς', 'give', 'aor act impv 2sg', 'δίδωμι'],
      ['ἡμῖν', 'to us', 'dat pl', 'ἐγώ'],
      ['σήμερον·', 'today', 'adv', 'σήμερον'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἄφες', 'forgive', 'aor act impv 2sg', 'ἀφίημι'],
      ['ἡμῖν', 'us', 'dat pl', 'ἐγώ'],
      ['τὰ', 'the', 'acc pl neut', 'ὁ'],
      ['ὀφειλήματα', 'debts', 'acc pl neut', 'ὀφείλημα, -ατος, τό'],
      ['ἡμῶν,', 'our', 'gen pl', 'ἐγώ'],
      ['ὡς', 'as', 'conj', 'ὡς'],
      ['καὶ', 'also', 'conj', 'καί'],
      ['ἡμεῖς', 'we', 'nom pl', 'ἐγώ'],
      ['ἀφήκαμεν', 'have forgiven', 'aor act ind 1pl', 'ἀφίημι'],
      ['τοῖς', 'the', 'dat pl masc', 'ὁ'],
      ['ὀφειλέταις', 'debtors', 'dat pl masc', 'ὀφειλέτης, -ου, ὁ'],
      ['ἡμῶν·', 'our', 'gen pl', 'ἐγώ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['μὴ', 'not', 'particle', 'μή'],
      ['εἰσενέγκῃς', 'bring in', 'aor act subj 2sg', 'εἰσφέρω'],
      ['ἡμᾶς', 'us', 'acc pl', 'ἐγώ'],
      ['εἰς', 'into', 'prep +acc', 'εἰς'],
      ['πειρασμόν,', 'testing, temptation', 'acc sg masc', 'πειρασμός, -οῦ, ὁ'],
      ['ἀλλὰ', 'but', 'conj', 'ἀλλά'],
      ['ῥῦσαι', 'rescue', 'aor mid impv 2sg', 'ῥύομαι'],
      ['ἡμᾶς', 'us', 'acc pl', 'ἐγώ'],
      ['ἀπὸ', 'from', 'prep +gen', 'ἀπό'],
      ['τοῦ', 'the', 'gen sg masc', 'ὁ'],
      ['πονηροῦ.', 'evil one', 'gen sg masc', 'πονηρός, -ά, -όν']
    ],
    note: 'μὴ + aorist subjunctive is how Greek forbids something outright ("do not ever ..."), where μή + present imperative would mean "stop doing it".'
  },
  {
    id: 'mt28-19', ref: 'Matthew 28:19–20', level: 3, title: 'Make disciples',
    en: 'Therefore, having gone, make disciples of all the nations, baptising them into the name of the Father and of the Son and of the Holy Spirit, teaching them to keep all that I commanded you; and behold, I am with you all the days until the completion of the age.',
    words: [
      ['πορευθέντες', 'having gone', 'aor pass ptc nom pl masc', 'πορεύομαι'],
      ['οὖν', 'therefore', 'conj', 'οὖν'],
      ['μαθητεύσατε', 'make disciples of', 'aor act impv 2pl', 'μαθητεύω'],
      ['πάντα', 'all', 'acc pl neut', 'πᾶς, πᾶσα, πᾶν'],
      ['τὰ', 'the', 'acc pl neut', 'ὁ'],
      ['ἔθνη,', 'nations', 'acc pl neut', 'ἔθνος, -ους, τό'],
      ['βαπτίζοντες', 'baptising', 'pres act ptc nom pl masc', 'βαπτίζω'],
      ['αὐτοὺς', 'them', 'acc pl masc', 'αὐτός'],
      ['εἰς', 'into', 'prep +acc', 'εἰς'],
      ['τὸ', 'the', 'acc sg neut', 'ὁ'],
      ['ὄνομα', 'name', 'acc sg neut', 'ὄνομα, -ατος, τό'],
      ['τοῦ', 'of the', 'gen sg masc', 'ὁ'],
      ['πατρὸς', 'Father', 'gen sg masc', 'πατήρ, πατρός, ὁ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['τοῦ', 'of the', 'gen sg masc', 'ὁ'],
      ['υἱοῦ', 'Son', 'gen sg masc', 'υἱός, -οῦ, ὁ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['τοῦ', 'of the', 'gen sg neut', 'ὁ'],
      ['ἁγίου', 'Holy', 'gen sg neut', 'ἅγιος, -ία, -ον'],
      ['πνεύματος,', 'Spirit', 'gen sg neut', 'πνεῦμα, -ατος, τό'],
      ['διδάσκοντες', 'teaching', 'pres act ptc nom pl masc', 'διδάσκω'],
      ['αὐτοὺς', 'them', 'acc pl masc', 'αὐτός'],
      ['τηρεῖν', 'to keep', 'pres act inf', 'τηρέω'],
      ['πάντα', 'all things', 'acc pl neut', 'πᾶς, πᾶσα, πᾶν'],
      ['ὅσα', 'as many as', 'acc pl neut', 'ὅσος, -η, -ον'],
      ['ἐνετειλάμην', 'I commanded', 'aor mid ind 1sg', 'ἐντέλλομαι'],
      ['ὑμῖν·', 'you', 'dat pl', 'σύ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἰδοὺ', 'behold', 'particle', 'ἰδού'],
      ['ἐγὼ', 'I', 'nom sg', 'ἐγώ'],
      ["μεθ'", 'with', 'prep +gen', 'μετά'],
      ['ὑμῶν', 'you', 'gen pl', 'σύ'],
      ['εἰμι', 'am', 'pres act ind 1sg', 'εἰμί'],
      ['πάσας', 'all', 'acc pl fem', 'πᾶς, πᾶσα, πᾶν'],
      ['τὰς', 'the', 'acc pl fem', 'ὁ'],
      ['ἡμέρας', 'days', 'acc pl fem', 'ἡμέρα, -ας, ἡ'],
      ['ἕως', 'until', 'prep +gen', 'ἕως'],
      ['τῆς', 'the', 'gen sg fem', 'ὁ'],
      ['συντελείας', 'completion', 'gen sg fem', 'συντέλεια, -ας, ἡ'],
      ['τοῦ', 'of the', 'gen sg masc', 'ὁ'],
      ['αἰῶνος.', 'age', 'gen sg masc', 'αἰών, -ῶνος, ὁ']
    ],
    note: 'Only μαθητεύσατε is an imperative. The three participles hang off it, so the command is "make disciples" — the rest tells you how.'
  },
  {
    id: 'rom3-23', ref: 'Romans 3:23', level: 1, title: 'All have sinned',
    en: 'For all sinned and fall short of the glory of God.',
    words: [
      ['πάντες', 'all', 'nom pl masc', 'πᾶς, πᾶσα, πᾶν'],
      ['γὰρ', 'for', 'conj', 'γάρ'],
      ['ἥμαρτον', 'sinned', 'aor act ind 3pl', 'ἁμαρτάνω'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ὑστεροῦνται', 'fall short of', 'pres mid ind 3pl', 'ὑστερέω'],
      ['τῆς', 'the', 'gen sg fem', 'ὁ'],
      ['δόξης', 'glory', 'gen sg fem', 'δόξα, -ης, ἡ'],
      ['τοῦ', 'of the', 'gen sg masc', 'ὁ'],
      ['θεοῦ', 'God', 'gen sg masc', 'θεός, -οῦ, ὁ']
    ],
    note: 'ὑστερέω takes a genitive of what is lacked. That is why "glory" is δόξης and not δόξαν.'
  },
  {
    id: 'rom5-8', ref: 'Romans 5:8', level: 3, title: 'While we were still sinners',
    en: 'But God demonstrates his own love toward us, in that while we were still sinners Christ died on our behalf.',
    words: [
      ['συνίστησιν', 'demonstrates', 'pres act ind 3sg', 'συνίστημι'],
      ['δὲ', 'but', 'conj', 'δέ'],
      ['τὴν', 'the', 'acc sg fem', 'ὁ'],
      ['ἑαυτοῦ', 'his own', 'gen sg masc', 'ἑαυτοῦ, -ῆς, -οῦ'],
      ['ἀγάπην', 'love', 'acc sg fem', 'ἀγάπη, -ης, ἡ'],
      ['εἰς', 'toward', 'prep +acc', 'εἰς'],
      ['ἡμᾶς', 'us', 'acc pl', 'ἐγώ'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['θεὸς', 'God', 'nom sg masc', 'θεός, -οῦ, ὁ'],
      ['ὅτι', 'in that', 'conj', 'ὅτι'],
      ['ἔτι', 'still', 'adv', 'ἔτι'],
      ['ἁμαρτωλῶν', 'sinners', 'gen pl masc', 'ἁμαρτωλός, -όν'],
      ['ὄντων', 'being', 'pres act ptc gen pl masc', 'εἰμί'],
      ['ἡμῶν', 'we', 'gen pl', 'ἐγώ'],
      ['Χριστὸς', 'Christ', 'nom sg masc', 'Χριστός, -οῦ, ὁ'],
      ['ὑπὲρ', 'on behalf of', 'prep +gen', 'ὑπέρ'],
      ['ἡμῶν', 'us', 'gen pl', 'ἐγώ'],
      ['ἀπέθανεν.', 'died', 'aor act ind 3sg', 'ἀποθνῄσκω']
    ],
    note: 'ἁμαρτωλῶν ὄντων ἡμῶν is a genitive absolute: a noun and participle in the genitive, grammatically detached from the main clause. Translate it "while we were ...".'
  },
  {
    id: 'rom6-23', ref: 'Romans 6:23', level: 1, title: 'The wages of sin',
    en: 'For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.',
    words: [
      ['τὰ', 'the', 'nom pl neut', 'ὁ'],
      ['γὰρ', 'for', 'conj', 'γάρ'],
      ['ὀψώνια', 'wages', 'nom pl neut', 'ὀψώνιον, -ου, τό'],
      ['τῆς', 'of the', 'gen sg fem', 'ὁ'],
      ['ἁμαρτίας', 'sin', 'gen sg fem', 'ἁμαρτία, -ας, ἡ'],
      ['θάνατος,', 'death', 'nom sg masc', 'θάνατος, -ου, ὁ'],
      ['τὸ', 'the', 'nom sg neut', 'ὁ'],
      ['δὲ', 'but', 'conj', 'δέ'],
      ['χάρισμα', 'free gift', 'nom sg neut', 'χάρισμα, -ατος, τό'],
      ['τοῦ', 'of the', 'gen sg masc', 'ὁ'],
      ['θεοῦ', 'God', 'gen sg masc', 'θεός, -οῦ, ὁ'],
      ['ζωὴ', 'life', 'nom sg fem', 'ζωή, -ῆς, ἡ'],
      ['αἰώνιος', 'eternal', 'nom sg fem', 'αἰώνιος, -ον'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['Χριστῷ', 'Christ', 'dat sg masc', 'Χριστός, -οῦ, ὁ'],
      ['Ἰησοῦ', 'Jesus', 'dat sg masc', 'Ἰησοῦς, -οῦ, ὁ'],
      ['τῷ', 'the', 'dat sg masc', 'ὁ'],
      ['κυρίῳ', 'Lord', 'dat sg masc', 'κύριος, -ου, ὁ'],
      ['ἡμῶν.', 'our', 'gen pl', 'ἐγώ']
    ],
    note: 'αἰώνιος is a two-termination adjective: one set of endings covers masculine and feminine, so a feminine ζωή takes the form that looks masculine.'
  },
  {
    id: 'rom8-28', ref: 'Romans 8:28', level: 3, title: 'All things work together',
    en: 'And we know that for those who love God all things work together for good, for those who are called according to purpose.',
    words: [
      ['οἴδαμεν', 'we know', 'perf act ind 1pl', 'οἶδα'],
      ['δὲ', 'and', 'conj', 'δέ'],
      ['ὅτι', 'that', 'conj', 'ὅτι'],
      ['τοῖς', 'for those', 'dat pl masc', 'ὁ'],
      ['ἀγαπῶσιν', 'loving', 'pres act ptc dat pl masc', 'ἀγαπάω'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['θεὸν', 'God', 'acc sg masc', 'θεός, -οῦ, ὁ'],
      ['πάντα', 'all things', 'nom pl neut', 'πᾶς, πᾶσα, πᾶν'],
      ['συνεργεῖ', 'works together', 'pres act ind 3sg', 'συνεργέω'],
      ['εἰς', 'for', 'prep +acc', 'εἰς'],
      ['ἀγαθόν,', 'good', 'acc sg neut', 'ἀγαθός, -ή, -όν'],
      ['τοῖς', 'for those', 'dat pl masc', 'ὁ'],
      ['κατὰ', 'according to', 'prep +acc', 'κατά'],
      ['πρόθεσιν', 'purpose', 'acc sg fem', 'πρόθεσις, -εως, ἡ'],
      ['κλητοῖς', 'called', 'dat pl masc', 'κλητός, -ή, -όν'],
      ['οὖσιν.', 'being', 'pres act ptc dat pl masc', 'εἰμί']
    ],
    note: 'πάντα is neuter plural and the verb συνεργεῖ is singular. Greek routinely puts a neuter plural subject with a singular verb — it is not a mistake.'
  },
  {
    id: 'rom10-9', ref: 'Romans 10:9', level: 3, title: 'If you confess',
    en: 'That if you confess with your mouth "Jesus is Lord" and believe in your heart that God raised him from the dead, you will be saved.',
    words: [
      ['ὅτι', 'that', 'conj', 'ὅτι'],
      ['ἐὰν', 'if', 'conj', 'ἐάν'],
      ['ὁμολογήσῃς', 'you confess', 'aor act subj 2sg', 'ὁμολογέω'],
      ['ἐν', 'with', 'prep +dat', 'ἐν'],
      ['τῷ', 'the', 'dat sg neut', 'ὁ'],
      ['στόματί', 'mouth', 'dat sg neut', 'στόμα, -ατος, τό'],
      ['σου', 'your', 'gen sg', 'σύ'],
      ['κύριον', 'Lord', 'acc sg masc', 'κύριος, -ου, ὁ'],
      ['Ἰησοῦν', 'Jesus', 'acc sg masc', 'Ἰησοῦς, -οῦ, ὁ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['πιστεύσῃς', 'you believe', 'aor act subj 2sg', 'πιστεύω'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['τῇ', 'the', 'dat sg fem', 'ὁ'],
      ['καρδίᾳ', 'heart', 'dat sg fem', 'καρδία, -ας, ἡ'],
      ['σου', 'your', 'gen sg', 'σύ'],
      ['ὅτι', 'that', 'conj', 'ὅτι'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['θεὸς', 'God', 'nom sg masc', 'θεός, -οῦ, ὁ'],
      ['αὐτὸν', 'him', 'acc sg masc', 'αὐτός'],
      ['ἤγειρεν', 'raised', 'aor act ind 3sg', 'ἐγείρω'],
      ['ἐκ', 'from', 'prep +gen', 'ἐκ'],
      ['νεκρῶν,', 'the dead', 'gen pl masc', 'νεκρός, -ά, -όν'],
      ['σωθήσῃ.', 'you will be saved', 'fut pass ind 2sg', 'σῴζω']
    ],
    note: 'ἐάν always drags the subjunctive along with it — that is why both verbs in the "if" clause are subjunctive.'
  },
  {
    id: '1cor13-13', ref: '1 Corinthians 13:13', level: 1, title: 'Faith, hope, love',
    en: 'And now there remain faith, hope, love — these three; but the greatest of these is love.',
    words: [
      ['νυνὶ', 'now', 'adv', 'νυνί'],
      ['δὲ', 'and', 'conj', 'δέ'],
      ['μένει', 'remains', 'pres act ind 3sg', 'μένω'],
      ['πίστις,', 'faith', 'nom sg fem', 'πίστις, -εως, ἡ'],
      ['ἐλπίς,', 'hope', 'nom sg fem', 'ἐλπίς, -ίδος, ἡ'],
      ['ἀγάπη,', 'love', 'nom sg fem', 'ἀγάπη, -ης, ἡ'],
      ['τὰ', 'the', 'nom pl neut', 'ὁ'],
      ['τρία', 'three', 'nom pl neut', 'τρεῖς, τρία'],
      ['ταῦτα·', 'these', 'nom pl neut', 'οὗτος'],
      ['μείζων', 'greater', 'nom sg fem', 'μείζων, -ον'],
      ['δὲ', 'but', 'conj', 'δέ'],
      ['τούτων', 'of these', 'gen pl neut', 'οὗτος'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['ἀγάπη.', 'love', 'nom sg fem', 'ἀγάπη, -ης, ἡ']
    ],
    note: 'τούτων is a genitive of comparison: "greater than these". Greek can use the genitive where English needs "than".'
  },
  {
    id: 'gal2-20', ref: 'Galatians 2:20', level: 3, title: 'No longer I who live',
    en: 'And it is no longer I who live, but Christ lives in me; and what I now live in the flesh, I live by faith in the Son of God, who loved me and gave himself up for me.',
    words: [
      ['ζῶ', 'I live', 'pres act ind 1sg', 'ζάω'],
      ['δὲ', 'and', 'conj', 'δέ'],
      ['οὐκέτι', 'no longer', 'adv', 'οὐκέτι'],
      ['ἐγώ,', 'I', 'nom sg', 'ἐγώ'],
      ['ζῇ', 'lives', 'pres act ind 3sg', 'ζάω'],
      ['δὲ', 'but', 'conj', 'δέ'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['ἐμοὶ', 'me', 'dat sg', 'ἐγώ'],
      ['Χριστός·', 'Christ', 'nom sg masc', 'Χριστός, -οῦ, ὁ'],
      ['ὃ', 'what', 'acc sg neut', 'ὅς, ἥ, ὅ'],
      ['δὲ', 'and', 'conj', 'δέ'],
      ['νῦν', 'now', 'adv', 'νῦν'],
      ['ζῶ', 'I live', 'pres act ind 1sg', 'ζάω'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['σαρκί,', 'flesh', 'dat sg fem', 'σάρξ, σαρκός, ἡ'],
      ['ἐν', 'by', 'prep +dat', 'ἐν'],
      ['πίστει', 'faith', 'dat sg fem', 'πίστις, -εως, ἡ'],
      ['ζῶ', 'I live', 'pres act ind 1sg', 'ζάω'],
      ['τῇ', 'the', 'dat sg fem', 'ὁ'],
      ['τοῦ', 'of the', 'gen sg masc', 'ὁ'],
      ['υἱοῦ', 'Son', 'gen sg masc', 'υἱός, -οῦ, ὁ'],
      ['τοῦ', 'of', 'gen sg masc', 'ὁ'],
      ['θεοῦ', 'God', 'gen sg masc', 'θεός, -οῦ, ὁ'],
      ['τοῦ', 'the one', 'gen sg masc', 'ὁ'],
      ['ἀγαπήσαντός', 'having loved', 'aor act ptc gen sg masc', 'ἀγαπάω'],
      ['με', 'me', 'acc sg', 'ἐγώ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['παραδόντος', 'having handed over', 'aor act ptc gen sg masc', 'παραδίδωμι'],
      ['ἑαυτὸν', 'himself', 'acc sg masc', 'ἑαυτοῦ, -ῆς, -οῦ'],
      ['ὑπὲρ', 'for', 'prep +gen', 'ὑπέρ'],
      ['ἐμοῦ.', 'me', 'gen sg', 'ἐγώ']
    ],
    note: 'τῇ ... τοῦ υἱοῦ τοῦ θεοῦ: the article τῇ agrees with πίστει far to its left, and everything between is stuffed inside. Greek does this constantly — follow the article, not the word order.'
  },
  {
    id: 'gal5-22', ref: 'Galatians 5:22–23', level: 2, title: 'The fruit of the Spirit',
    en: 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control; against such things there is no law.',
    words: [
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['δὲ', 'but', 'conj', 'δέ'],
      ['καρπὸς', 'fruit', 'nom sg masc', 'καρπός, -οῦ, ὁ'],
      ['τοῦ', 'of the', 'gen sg neut', 'ὁ'],
      ['πνεύματός', 'Spirit', 'gen sg neut', 'πνεῦμα, -ατος, τό'],
      ['ἐστιν', 'is', 'pres act ind 3sg', 'εἰμί'],
      ['ἀγάπη,', 'love', 'nom sg fem', 'ἀγάπη, -ης, ἡ'],
      ['χαρά,', 'joy', 'nom sg fem', 'χαρά, -ᾶς, ἡ'],
      ['εἰρήνη,', 'peace', 'nom sg fem', 'εἰρήνη, -ης, ἡ'],
      ['μακροθυμία,', 'patience', 'nom sg fem', 'μακροθυμία, -ας, ἡ'],
      ['χρηστότης,', 'kindness', 'nom sg fem', 'χρηστότης, -ητος, ἡ'],
      ['ἀγαθωσύνη,', 'goodness', 'nom sg fem', 'ἀγαθωσύνη, -ης, ἡ'],
      ['πίστις,', 'faithfulness', 'nom sg fem', 'πίστις, -εως, ἡ'],
      ['πραΰτης,', 'gentleness', 'nom sg fem', 'πραΰτης, -ητος, ἡ'],
      ['ἐγκράτεια·', 'self-control', 'nom sg fem', 'ἐγκράτεια, -ας, ἡ'],
      ['κατὰ', 'against', 'prep +gen', 'κατά'],
      ['τῶν', 'the', 'gen pl neut', 'ὁ'],
      ['τοιούτων', 'such things', 'gen pl neut', 'τοιοῦτος, -αύτη, -οῦτο'],
      ['οὐκ', 'not', 'adv', 'οὐ'],
      ['ἔστιν', 'is', 'pres act ind 3sg', 'εἰμί'],
      ['νόμος.', 'law', 'nom sg masc', 'νόμος, -ου, ὁ']
    ],
    note: 'καρπὸς is singular although nine things follow. One fruit, nine facets.'
  },
  {
    id: 'eph2-8', ref: 'Ephesians 2:8–9', level: 3, title: 'By grace you have been saved',
    en: 'For by grace you have been saved through faith; and this is not from you, it is the gift of God — not from works, so that no one may boast.',
    words: [
      ['Τῇ', 'by the', 'dat sg fem', 'ὁ'],
      ['γὰρ', 'for', 'conj', 'γάρ'],
      ['χάριτί', 'grace', 'dat sg fem', 'χάρις, -ιτος, ἡ'],
      ['ἐστε', 'you are', 'pres act ind 2pl', 'εἰμί'],
      ['σεσῳσμένοι', 'having been saved', 'perf pass ptc nom pl masc', 'σῴζω'],
      ['διὰ', 'through', 'prep +gen', 'διά'],
      ['πίστεως·', 'faith', 'gen sg fem', 'πίστις, -εως, ἡ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['τοῦτο', 'this', 'nom sg neut', 'οὗτος'],
      ['οὐκ', 'not', 'adv', 'οὐ'],
      ['ἐξ', 'from', 'prep +gen', 'ἐκ'],
      ['ὑμῶν,', 'you', 'gen pl', 'σύ'],
      ['θεοῦ', 'of God', 'gen sg masc', 'θεός, -οῦ, ὁ'],
      ['τὸ', 'the', 'nom sg neut', 'ὁ'],
      ['δῶρον·', 'gift', 'nom sg neut', 'δῶρον, -ου, τό'],
      ['οὐκ', 'not', 'adv', 'οὐ'],
      ['ἐξ', 'from', 'prep +gen', 'ἐκ'],
      ['ἔργων,', 'works', 'gen pl neut', 'ἔργον, -ου, τό'],
      ['ἵνα', 'so that', 'conj', 'ἵνα'],
      ['μή', 'not', 'particle', 'μή'],
      ['τις', 'anyone', 'nom sg masc', 'τις, τι'],
      ['καυχήσηται.', 'may boast', 'aor mid subj 3sg', 'καυχάομαι']
    ],
    note: 'ἐστε σεσῳσμένοι is a periphrastic perfect: εἰμί plus a perfect participle, doing the work of one perfect verb. The state, not the event, is in view.'
  },
  {
    id: 'php4-13', ref: 'Philippians 4:13', level: 1, title: 'I am strong for all things',
    en: 'I am strong for all things in the one who strengthens me.',
    words: [
      ['πάντα', 'all things', 'acc pl neut', 'πᾶς, πᾶσα, πᾶν'],
      ['ἰσχύω', 'I am strong, I can do', 'pres act ind 1sg', 'ἰσχύω'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['τῷ', 'the one', 'dat sg masc', 'ὁ'],
      ['ἐνδυναμοῦντί', 'strengthening', 'pres act ptc dat sg masc', 'ἐνδυναμόω'],
      ['με', 'me', 'acc sg', 'ἐγώ']
    ],
    note: 'Six words. Note τῷ ἐνδυναμοῦντί — an article plus participle makes a noun: "the one who strengthens".'
  },
  {
    id: 'php4-6', ref: 'Philippians 4:6', level: 3, title: 'Be anxious for nothing',
    en: 'Be anxious about nothing, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.',
    words: [
      ['μηδὲν', 'nothing', 'acc sg neut', 'μηδείς, μηδεμία, μηδέν'],
      ['μεριμνᾶτε,', 'be anxious', 'pres act impv 2pl', 'μεριμνάω'],
      ["ἀλλ'", 'but', 'conj', 'ἀλλά'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['παντὶ', 'everything', 'dat sg neut', 'πᾶς, πᾶσα, πᾶν'],
      ['τῇ', 'by the', 'dat sg fem', 'ὁ'],
      ['προσευχῇ', 'prayer', 'dat sg fem', 'προσευχή, -ῆς, ἡ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['τῇ', 'the', 'dat sg fem', 'ὁ'],
      ['δεήσει', 'petition', 'dat sg fem', 'δέησις, -εως, ἡ'],
      ['μετὰ', 'with', 'prep +gen', 'μετά'],
      ['εὐχαριστίας', 'thanksgiving', 'gen sg fem', 'εὐχαριστία, -ας, ἡ'],
      ['τὰ', 'the', 'nom pl neut', 'ὁ'],
      ['αἰτήματα', 'requests', 'nom pl neut', 'αἴτημα, -ατος, τό'],
      ['ὑμῶν', 'your', 'gen pl', 'σύ'],
      ['γνωριζέσθω', 'let be made known', 'pres pass impv 3sg', 'γνωρίζω'],
      ['πρὸς', 'to', 'prep +acc', 'πρός'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['θεόν.', 'God', 'acc sg masc', 'θεός, -οῦ, ὁ']
    ],
    note: 'μηδὲν μεριμνᾶτε is μή + present imperative: stop an activity already under way, or refuse it as a habit.'
  },
  {
    id: '1jn1-9', ref: '1 John 1:9', level: 2, title: 'If we confess our sins',
    en: 'If we confess our sins, he is faithful and righteous, so that he forgives us the sins and cleanses us from all unrighteousness.',
    words: [
      ['ἐὰν', 'if', 'conj', 'ἐάν'],
      ['ὁμολογῶμεν', 'we confess', 'pres act subj 1pl', 'ὁμολογέω'],
      ['τὰς', 'the', 'acc pl fem', 'ὁ'],
      ['ἁμαρτίας', 'sins', 'acc pl fem', 'ἁμαρτία, -ας, ἡ'],
      ['ἡμῶν,', 'our', 'gen pl', 'ἐγώ'],
      ['πιστός', 'faithful', 'nom sg masc', 'πιστός, -ή, -όν'],
      ['ἐστιν', 'he is', 'pres act ind 3sg', 'εἰμί'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['δίκαιος', 'righteous', 'nom sg masc', 'δίκαιος, -αία, -ον'],
      ['ἵνα', 'so that', 'conj', 'ἵνα'],
      ['ἀφῇ', 'he may forgive', 'aor act subj 3sg', 'ἀφίημι'],
      ['ἡμῖν', 'us', 'dat pl', 'ἐγώ'],
      ['τὰς', 'the', 'acc pl fem', 'ὁ'],
      ['ἁμαρτίας', 'sins', 'acc pl fem', 'ἁμαρτία, -ας, ἡ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['καθαρίσῃ', 'he may cleanse', 'aor act subj 3sg', 'καθαρίζω'],
      ['ἡμᾶς', 'us', 'acc pl', 'ἐγώ'],
      ['ἀπὸ', 'from', 'prep +gen', 'ἀπό'],
      ['πάσης', 'all', 'gen sg fem', 'πᾶς, πᾶσα, πᾶν'],
      ['ἀδικίας.', 'unrighteousness', 'gen sg fem', 'ἀδικία, -ας, ἡ']
    ]
  },
  {
    id: '1jn4-7', ref: '1 John 4:7–8', level: 2, title: 'Love is from God',
    en: 'Beloved, let us love one another, because love is from God, and everyone who loves has been born from God and knows God. The one who does not love did not know God, because God is love.',
    words: [
      ['Ἀγαπητοί,', 'beloved', 'voc pl masc', 'ἀγαπητός, -ή, -όν'],
      ['ἀγαπῶμεν', 'let us love', 'pres act subj 1pl', 'ἀγαπάω'],
      ['ἀλλήλους,', 'one another', 'acc pl masc', 'ἀλλήλων'],
      ['ὅτι', 'because', 'conj', 'ὅτι'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['ἀγάπη', 'love', 'nom sg fem', 'ἀγάπη, -ης, ἡ'],
      ['ἐκ', 'from', 'prep +gen', 'ἐκ'],
      ['τοῦ', 'the', 'gen sg masc', 'ὁ'],
      ['θεοῦ', 'God', 'gen sg masc', 'θεός, -οῦ, ὁ'],
      ['ἐστιν,', 'is', 'pres act ind 3sg', 'εἰμί'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['πᾶς', 'everyone', 'nom sg masc', 'πᾶς, πᾶσα, πᾶν'],
      ['ὁ', 'the one', 'nom sg masc', 'ὁ'],
      ['ἀγαπῶν', 'loving', 'pres act ptc nom sg masc', 'ἀγαπάω'],
      ['ἐκ', 'from', 'prep +gen', 'ἐκ'],
      ['τοῦ', 'the', 'gen sg masc', 'ὁ'],
      ['θεοῦ', 'God', 'gen sg masc', 'θεός, -οῦ, ὁ'],
      ['γεγέννηται', 'has been born', 'perf pass ind 3sg', 'γεννάω'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['γινώσκει', 'knows', 'pres act ind 3sg', 'γινώσκω'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['θεόν.', 'God', 'acc sg masc', 'θεός, -οῦ, ὁ'],
      ['ὁ', 'the one', 'nom sg masc', 'ὁ'],
      ['μὴ', 'not', 'particle', 'μή'],
      ['ἀγαπῶν', 'loving', 'pres act ptc nom sg masc', 'ἀγαπάω'],
      ['οὐκ', 'not', 'adv', 'οὐ'],
      ['ἔγνω', 'knew', 'aor act ind 3sg', 'γινώσκω'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['θεόν,', 'God', 'acc sg masc', 'θεός, -οῦ, ὁ'],
      ['ὅτι', 'because', 'conj', 'ὅτι'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['θεὸς', 'God', 'nom sg masc', 'θεός, -οῦ, ὁ'],
      ['ἀγάπη', 'love', 'nom sg fem', 'ἀγάπη, -ης, ἡ'],
      ['ἐστίν.', 'is', 'pres act ind 3sg', 'εἰμί']
    ],
    note: 'ἀγαπῶμεν is ambiguous in form — present indicative "we love" or present subjunctive "let us love". Only the context decides, and here the hortatory reading fits.'
  },
  {
    id: 'heb11-1', ref: 'Hebrews 11:1', level: 3, title: 'Now faith is',
    en: 'Now faith is the substance of things hoped for, the proof of things not seen.',
    words: [
      ['Ἔστιν', 'is', 'pres act ind 3sg', 'εἰμί'],
      ['δὲ', 'now', 'conj', 'δέ'],
      ['πίστις', 'faith', 'nom sg fem', 'πίστις, -εως, ἡ'],
      ['ἐλπιζομένων', 'of things being hoped for', 'pres pass ptc gen pl neut', 'ἐλπίζω'],
      ['ὑπόστασις,', 'substance, assurance', 'nom sg fem', 'ὑπόστασις, -εως, ἡ'],
      ['πραγμάτων', 'of things', 'gen pl neut', 'πρᾶγμα, -ατος, τό'],
      ['ἔλεγχος', 'proof, conviction', 'nom sg masc', 'ἔλεγχος, -ου, ὁ'],
      ['οὐ', 'not', 'adv', 'οὐ'],
      ['βλεπομένων.', 'being seen', 'pres pass ptc gen pl neut', 'βλέπω']
    ],
    note: 'Both participles are genitive plural neuter with no noun — the article-less participle simply means "things that are ...".'
  },
  {
    id: 'jn14-6', ref: 'John 14:6', level: 1, title: 'I am the way',
    en: 'Jesus says to him: I am the way and the truth and the life; no one comes to the Father except through me.',
    words: [
      ['λέγει', 'says', 'pres act ind 3sg', 'λέγω'],
      ['αὐτῷ', 'to him', 'dat sg masc', 'αὐτός'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['Ἰησοῦς·', 'Jesus', 'nom sg masc', 'Ἰησοῦς, -οῦ, ὁ'],
      ['Ἐγώ', 'I', 'nom sg', 'ἐγώ'],
      ['εἰμι', 'am', 'pres act ind 1sg', 'εἰμί'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['ὁδὸς', 'way', 'nom sg fem', 'ὁδός, -οῦ, ἡ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['ἀλήθεια', 'truth', 'nom sg fem', 'ἀλήθεια, -ας, ἡ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['ζωή·', 'life', 'nom sg fem', 'ζωή, -ῆς, ἡ'],
      ['οὐδεὶς', 'no one', 'nom sg masc', 'οὐδείς, οὐδεμία, οὐδέν'],
      ['ἔρχεται', 'comes', 'pres mid ind 3sg', 'ἔρχομαι'],
      ['πρὸς', 'to', 'prep +acc', 'πρός'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['πατέρα', 'Father', 'acc sg masc', 'πατήρ, πατρός, ὁ'],
      ['εἰ', 'if', 'conj', 'εἰ'],
      ['μὴ', 'not', 'particle', 'μή'],
      ["δι'", 'through', 'prep +gen', 'διά'],
      ['ἐμοῦ.', 'me', 'gen sg', 'ἐγώ']
    ],
    note: 'εἰ μή together simply means "except". ὁδός is one of those second-declension nouns that is feminine — the article ἡ tells you so.'
  },
  {
    id: 'jn15-5', ref: 'John 15:5', level: 3, title: 'I am the vine',
    en: 'I am the vine, you are the branches. The one who abides in me and I in him, this one bears much fruit, because apart from me you can do nothing.',
    words: [
      ['ἐγώ', 'I', 'nom sg', 'ἐγώ'],
      ['εἰμι', 'am', 'pres act ind 1sg', 'εἰμί'],
      ['ἡ', 'the', 'nom sg fem', 'ὁ'],
      ['ἄμπελος,', 'vine', 'nom sg fem', 'ἄμπελος, -ου, ἡ'],
      ['ὑμεῖς', 'you', 'nom pl', 'σύ'],
      ['τὰ', 'the', 'nom pl neut', 'ὁ'],
      ['κλήματα.', 'branches', 'nom pl neut', 'κλῆμα, -ατος, τό'],
      ['ὁ', 'the one', 'nom sg masc', 'ὁ'],
      ['μένων', 'abiding', 'pres act ptc nom sg masc', 'μένω'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['ἐμοὶ', 'me', 'dat sg', 'ἐγώ'],
      ['κἀγὼ', 'and I', 'nom sg (crasis καί + ἐγώ)', 'ἐγώ'],
      ['ἐν', 'in', 'prep +dat', 'ἐν'],
      ['αὐτῷ', 'him', 'dat sg masc', 'αὐτός'],
      ['οὗτος', 'this one', 'nom sg masc', 'οὗτος'],
      ['φέρει', 'bears', 'pres act ind 3sg', 'φέρω'],
      ['καρπὸν', 'fruit', 'acc sg masc', 'καρπός, -οῦ, ὁ'],
      ['πολύν,', 'much', 'acc sg masc', 'πολύς, πολλή, πολύ'],
      ['ὅτι', 'because', 'conj', 'ὅτι'],
      ['χωρὶς', 'apart from', 'prep +gen', 'χωρίς'],
      ['ἐμοῦ', 'me', 'gen sg', 'ἐγώ'],
      ['οὐ', 'not', 'adv', 'οὐ'],
      ['δύνασθε', 'you are able', 'pres mid ind 2pl', 'δύναμαι'],
      ['ποιεῖν', 'to do', 'pres act inf', 'ποιέω'],
      ['οὐδέν.', 'nothing', 'acc sg neut', 'οὐδείς, οὐδεμία, οὐδέν']
    ],
    note: 'οὐ ... οὐδέν is a double negative that strengthens rather than cancels: "you can do nothing at all".'
  },
  {
    id: 'mt22-37', ref: 'Matthew 22:37', level: 2, title: 'The great commandment',
    en: 'You shall love the Lord your God with your whole heart and with your whole soul and with your whole mind.',
    words: [
      ['ἀγαπήσεις', 'you shall love', 'fut act ind 2sg', 'ἀγαπάω'],
      ['κύριον', 'Lord', 'acc sg masc', 'κύριος, -ου, ὁ'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['θεόν', 'God', 'acc sg masc', 'θεός, -οῦ, ὁ'],
      ['σου', 'your', 'gen sg', 'σύ'],
      ['ἐν', 'with', 'prep +dat', 'ἐν'],
      ['ὅλῃ', 'whole', 'dat sg fem', 'ὅλος, -η, -ον'],
      ['τῇ', 'the', 'dat sg fem', 'ὁ'],
      ['καρδίᾳ', 'heart', 'dat sg fem', 'καρδία, -ας, ἡ'],
      ['σου', 'your', 'gen sg', 'σύ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἐν', 'with', 'prep +dat', 'ἐν'],
      ['ὅλῃ', 'whole', 'dat sg fem', 'ὅλος, -η, -ον'],
      ['τῇ', 'the', 'dat sg fem', 'ὁ'],
      ['ψυχῇ', 'soul', 'dat sg fem', 'ψυχή, -ῆς, ἡ'],
      ['σου', 'your', 'gen sg', 'σύ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἐν', 'with', 'prep +dat', 'ἐν'],
      ['ὅλῃ', 'whole', 'dat sg fem', 'ὅλος, -η, -ον'],
      ['τῇ', 'the', 'dat sg fem', 'ὁ'],
      ['διανοίᾳ', 'mind', 'dat sg fem', 'διάνοια, -ας, ἡ'],
      ['σου.', 'your', 'gen sg', 'σύ']
    ],
    note: 'A future indicative used as a command — Greek borrows this straight from the Hebrew of the Old Testament.'
  },
  {
    id: '1tim2-5', ref: '1 Timothy 2:5', level: 1, title: 'One God, one mediator',
    en: 'For God is one, and one is the mediator between God and men, a man, Christ Jesus.',
    words: [
      ['εἷς', 'one', 'nom sg masc', 'εἷς, μία, ἕν'],
      ['γὰρ', 'for', 'conj', 'γάρ'],
      ['θεός,', 'God', 'nom sg masc', 'θεός, -οῦ, ὁ'],
      ['εἷς', 'one', 'nom sg masc', 'εἷς, μία, ἕν'],
      ['καὶ', 'also', 'conj', 'καί'],
      ['μεσίτης', 'mediator', 'nom sg masc', 'μεσίτης, -ου, ὁ'],
      ['θεοῦ', 'of God', 'gen sg masc', 'θεός, -οῦ, ὁ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['ἀνθρώπων,', 'of men', 'gen pl masc', 'ἄνθρωπος, -ου, ὁ'],
      ['ἄνθρωπος', 'a man', 'nom sg masc', 'ἄνθρωπος, -ου, ὁ'],
      ['Χριστὸς', 'Christ', 'nom sg masc', 'Χριστός, -οῦ, ὁ'],
      ['Ἰησοῦς', 'Jesus', 'nom sg masc', 'Ἰησοῦς, -οῦ, ὁ']
    ]
  },
  {
    id: 'gen1-1', ref: 'Genesis 1:1 (LXX)', level: 1, title: 'In the beginning God made',
    en: 'In the beginning God made the heaven and the earth.',
    words: [
      ['Ἐν', 'in', 'prep +dat', 'ἐν'],
      ['ἀρχῇ', 'beginning', 'dat sg fem', 'ἀρχή, -ῆς, ἡ'],
      ['ἐποίησεν', 'made', 'aor act ind 3sg', 'ποιέω'],
      ['ὁ', 'the', 'nom sg masc', 'ὁ'],
      ['θεὸς', 'God', 'nom sg masc', 'θεός, -οῦ, ὁ'],
      ['τὸν', 'the', 'acc sg masc', 'ὁ'],
      ['οὐρανὸν', 'heaven', 'acc sg masc', 'οὐρανός, -οῦ, ὁ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['τὴν', 'the', 'acc sg fem', 'ὁ'],
      ['γῆν.', 'earth', 'acc sg fem', 'γῆ, γῆς, ἡ']
    ],
    note: 'The Septuagint opens with the same three words as John 1:1 — Ἐν ἀρχῇ. John is quoting Genesis on purpose.'
  },
  {
    id: 'ps22-1', ref: 'Psalm 22:1 LXX (23:1)', level: 1, title: 'The Lord shepherds me',
    en: 'The Lord shepherds me, and I will lack nothing.',
    words: [
      ['Κύριος', 'the Lord', 'nom sg masc', 'κύριος, -ου, ὁ'],
      ['ποιμαίνει', 'shepherds', 'pres act ind 3sg', 'ποιμαίνω'],
      ['με,', 'me', 'acc sg', 'ἐγώ'],
      ['καὶ', 'and', 'conj', 'καί'],
      ['οὐδέν', 'nothing', 'nom sg neut', 'οὐδείς, οὐδεμία, οὐδέν'],
      ['με', 'me', 'acc sg', 'ἐγώ'],
      ['ὑστερήσει.', 'will be lacking to', 'fut act ind 3sg', 'ὑστερέω']
    ],
    note: 'Literally "nothing will be lacking to me" — the Greek makes οὐδέν the subject, not the object.'
  }
];
