/* data-vocab.js — high-frequency New Testament vocabulary.
   freq = approximate number of occurrences in the Greek NT; it is there to
   order your effort, not to be quoted as a statistic. */
var GK = window.GK || {}; window.GK = GK;

GK.vocab = [
  { g: 'ὁ, ἡ, τό', e: 'the', pos: 'article', freq: 19870 },
  { g: 'καί', e: 'and, even, also', pos: 'conjunction', freq: 9161 },
  { g: 'αὐτός, -ή, -ό', e: 'he, she, it; himself; same', pos: 'pronoun', freq: 5595 },
  { g: 'σύ', e: 'you', pos: 'pronoun', freq: 2905 },
  { g: 'δέ', e: 'but, and', pos: 'conjunction', freq: 2792 },
  { g: 'ἐν', e: 'in, on, among (+ dat)', pos: 'preposition', freq: 2752 },
  { g: 'ἐγώ', e: 'I', pos: 'pronoun', freq: 2666 },
  { g: 'εἰμί', e: 'I am, exist', pos: 'verb', freq: 2460 },
  { g: 'λέγω', e: 'I say, speak', pos: 'verb', freq: 2354 },
  { g: 'εἰς', e: 'into, toward (+ acc)', pos: 'preposition', freq: 1767 },
  { g: 'οὐ, οὐκ, οὐχ', e: 'not', pos: 'adverb', freq: 1606 },
  { g: 'οὗτος, αὕτη, τοῦτο', e: 'this; he, she, it', pos: 'pronoun', freq: 1388 },
  { g: 'ὅς, ἥ, ὅ', e: 'who, which, that', pos: 'pronoun', freq: 1365 },
  { g: 'θεός, -οῦ, ὁ', e: 'God, god', pos: 'noun', freq: 1317 },
  { g: 'ὅτι', e: 'that, because', pos: 'conjunction', freq: 1296 },
  { g: 'πᾶς, πᾶσα, πᾶν', e: 'each, every; all', pos: 'adjective', freq: 1243 },
  { g: 'μή', e: 'not, lest', pos: 'particle', freq: 1042 },
  { g: 'γάρ', e: 'for, then', pos: 'conjunction', freq: 1041 },
  { g: 'Ἰησοῦς, -οῦ, ὁ', e: 'Jesus, Joshua', pos: 'noun', freq: 917 },
  { g: 'ἐκ, ἐξ', e: 'from, out of (+ gen)', pos: 'preposition', freq: 914 },
  { g: 'ἐπί', e: 'on, over, when (+ gen, dat, acc)', pos: 'preposition', freq: 890 },
  { g: 'κύριος, -ου, ὁ', e: 'Lord, lord, master, sir', pos: 'noun', freq: 717 },
  { g: 'ἔχω', e: 'I have, hold', pos: 'verb', freq: 708 },
  { g: 'πρός', e: 'to, toward, with (+ acc)', pos: 'preposition', freq: 700 },
  { g: 'γίνομαι', e: 'I become, am, happen', pos: 'verb', freq: 669 },
  { g: 'διά', e: 'through (+ gen); on account of (+ acc)', pos: 'preposition', freq: 667 },
  { g: 'ἵνα', e: 'in order that, that', pos: 'conjunction', freq: 663 },
  { g: 'ἀπό', e: 'from (+ gen)', pos: 'preposition', freq: 646 },
  { g: 'ἀλλά', e: 'but, yet, rather', pos: 'conjunction', freq: 638 },
  { g: 'ἔρχομαι', e: 'I come, go', pos: 'verb', freq: 634 },
  { g: 'ποιέω', e: 'I do, make', pos: 'verb', freq: 568 },
  { g: 'τίς, τί', e: 'who? what? why?', pos: 'pronoun', freq: 555 },
  { g: 'ἄνθρωπος, -ου, ὁ', e: 'man, person, humankind', pos: 'noun', freq: 550 },
  { g: 'Χριστός, -οῦ, ὁ', e: 'Christ, Messiah, Anointed One', pos: 'noun', freq: 529 },
  { g: 'τις, τι', e: 'someone, something, a certain', pos: 'pronoun', freq: 525 },
  { g: 'ὡς', e: 'as, like, when, about', pos: 'conjunction', freq: 504 },
  { g: 'εἰ', e: 'if', pos: 'conjunction', freq: 502 },
  { g: 'οὖν', e: 'therefore, then', pos: 'conjunction', freq: 498 },
  { g: 'κατά', e: 'down from (+ gen); according to (+ acc)', pos: 'preposition', freq: 473 },
  { g: 'μετά', e: 'with (+ gen); after (+ acc)', pos: 'preposition', freq: 469 },
  { g: 'ὁράω', e: 'I see, notice', pos: 'verb', freq: 454 },
  { g: 'ἀκούω', e: 'I hear, obey', pos: 'verb', freq: 428 },
  { g: 'πολύς, πολλή, πολύ', e: 'much, many; often', pos: 'adjective', freq: 416 },
  { g: 'δίδωμι', e: 'I give, grant', pos: 'verb', freq: 415 },
  { g: 'πατήρ, πατρός, ὁ', e: 'father', pos: 'noun', freq: 413 },
  { g: 'ἡμέρα, -ας, ἡ', e: 'day', pos: 'noun', freq: 389 },
  { g: 'πνεῦμα, -ατος, τό', e: 'spirit, Spirit, wind, breath', pos: 'noun', freq: 379 },
  { g: 'υἱός, -οῦ, ὁ', e: 'son, descendant', pos: 'noun', freq: 377 },
  { g: 'εἷς, μία, ἕν', e: 'one', pos: 'adjective', freq: 345 },
  { g: 'ἀδελφός, -οῦ, ὁ', e: 'brother', pos: 'noun', freq: 343 },
  { g: 'ἤ', e: 'or, than', pos: 'conjunction', freq: 343 },
  { g: 'περί', e: 'concerning (+ gen); around (+ acc)', pos: 'preposition', freq: 333 },
  { g: 'λόγος, -ου, ὁ', e: 'word, statement, message', pos: 'noun', freq: 330 },
  { g: 'ἑαυτοῦ, -ῆς, -οῦ', e: 'himself, herself, itself', pos: 'pronoun', freq: 319 },
  { g: 'οἶδα', e: 'I know, understand', pos: 'verb', freq: 318 },
  { g: 'λαλέω', e: 'I speak, say', pos: 'verb', freq: 296 },
  { g: 'οὐρανός, -οῦ, ὁ', e: 'heaven, sky', pos: 'noun', freq: 273 },
  { g: 'ἐκεῖνος, -η, -ο', e: 'that; he, she, it', pos: 'pronoun', freq: 265 },
  { g: 'μαθητής, -οῦ, ὁ', e: 'disciple', pos: 'noun', freq: 261 },
  { g: 'λαμβάνω', e: 'I take, receive', pos: 'verb', freq: 258 },
  { g: 'γῆ, γῆς, ἡ', e: 'earth, land, region', pos: 'noun', freq: 250 },
  { g: 'μέγας, μεγάλη, μέγα', e: 'large, great', pos: 'adjective', freq: 243 },
  { g: 'πίστις, -εως, ἡ', e: 'faith, faithfulness', pos: 'noun', freq: 243 },
  { g: 'πιστεύω', e: 'I believe, have faith in', pos: 'verb', freq: 241 },
  { g: 'οὐδέ', e: 'and not, neither, nor', pos: 'conjunction', freq: 143 },
  { g: 'ἅγιος, -ία, -ον', e: 'holy; (pl) saints', pos: 'adjective', freq: 233 },
  { g: 'ἀποκρίνομαι', e: 'I answer', pos: 'verb', freq: 231 },
  { g: 'ὄνομα, -ατος, τό', e: 'name, reputation', pos: 'noun', freq: 231 },
  { g: 'γινώσκω', e: 'I know, come to know', pos: 'verb', freq: 222 },
  { g: 'ὑπό', e: 'by (+ gen); under (+ acc)', pos: 'preposition', freq: 220 },
  { g: 'ἐξέρχομαι', e: 'I go out', pos: 'verb', freq: 218 },
  { g: 'ἀνήρ, ἀνδρός, ὁ', e: 'man, husband', pos: 'noun', freq: 216 },
  { g: 'γυνή, γυναικός, ἡ', e: 'woman, wife', pos: 'noun', freq: 215 },
  { g: 'τε', e: 'and (so), so', pos: 'conjunction', freq: 215 },
  { g: 'δύναμαι', e: 'I am able, can', pos: 'verb', freq: 210 },
  { g: 'θέλω', e: 'I wish, will, desire', pos: 'verb', freq: 208 },
  { g: 'οὕτως', e: 'thus, so, in this manner', pos: 'adverb', freq: 208 },
  { g: 'ἰδού', e: 'behold! look!', pos: 'particle', freq: 200 },
  { g: 'Ἰουδαῖος, -αία, -αῖον', e: 'Jewish; a Jew', pos: 'adjective', freq: 195 },
  { g: 'εἰσέρχομαι', e: 'I go in, enter', pos: 'verb', freq: 194 },
  { g: 'νόμος, -ου, ὁ', e: 'law, principle', pos: 'noun', freq: 194 },
  { g: 'παρά', e: 'from (+ gen); beside (+ dat); alongside (+ acc)', pos: 'preposition', freq: 194 },
  { g: 'γράφω', e: 'I write', pos: 'verb', freq: 191 },
  { g: 'κόσμος, -ου, ὁ', e: 'world, universe, humankind', pos: 'noun', freq: 186 },
  { g: 'καθώς', e: 'as, even as', pos: 'conjunction', freq: 182 },
  { g: 'μέν', e: 'on the one hand, indeed', pos: 'particle', freq: 179 },
  { g: 'χείρ, χειρός, ἡ', e: 'hand, arm, finger', pos: 'noun', freq: 177 },
  { g: 'εὑρίσκω', e: 'I find', pos: 'verb', freq: 176 },
  { g: 'ἄγγελος, -ου, ὁ', e: 'angel, messenger', pos: 'noun', freq: 175 },
  { g: 'ὄχλος, -ου, ὁ', e: 'crowd, multitude', pos: 'noun', freq: 175 },
  { g: 'ἁμαρτία, -ας, ἡ', e: 'sin', pos: 'noun', freq: 173 },
  { g: 'ἔργον, -ου, τό', e: 'work, deed, action', pos: 'noun', freq: 169 },
  { g: 'ἄν', e: '(untranslatable particle of contingency)', pos: 'particle', freq: 166 },
  { g: 'δόξα, -ης, ἡ', e: 'glory, majesty, fame', pos: 'noun', freq: 166 },
  { g: 'βασιλεία, -ας, ἡ', e: 'kingdom, reign', pos: 'noun', freq: 162 },
  { g: 'ἔθνος, -ους, τό', e: 'nation; (pl) Gentiles', pos: 'noun', freq: 162 },
  { g: 'πόλις, -εως, ἡ', e: 'city', pos: 'noun', freq: 162 },
  { g: 'τότε', e: 'then, thereafter', pos: 'adverb', freq: 160 },
  { g: 'ἐσθίω', e: 'I eat', pos: 'verb', freq: 158 },
  { g: 'Παῦλος, -ου, ὁ', e: 'Paul', pos: 'noun', freq: 158 },
  { g: 'καρδία, -ας, ἡ', e: 'heart, inner self', pos: 'noun', freq: 156 },
  { g: 'Πέτρος, -ου, ὁ', e: 'Peter', pos: 'noun', freq: 156 },
  { g: 'ἄλλος, -η, -ο', e: 'other, another', pos: 'adjective', freq: 155 },
  { g: 'πρῶτος, -η, -ον', e: 'first, earlier', pos: 'adjective', freq: 155 },
  { g: 'ἵστημι', e: 'I stand, set', pos: 'verb', freq: 154 },
  { g: 'πορεύομαι', e: 'I go, proceed, live', pos: 'verb', freq: 153 },
  { g: 'ὑπέρ', e: 'on behalf of (+ gen); above (+ acc)', pos: 'preposition', freq: 150 },
  { g: 'καλέω', e: 'I call, name, invite', pos: 'verb', freq: 148 },
  { g: 'νῦν', e: 'now, the present', pos: 'adverb', freq: 147 },
  { g: 'σάρξ, σαρκός, ἡ', e: 'flesh, body', pos: 'noun', freq: 147 },
  { g: 'ἕως', e: 'until, as far as', pos: 'conjunction', freq: 146 },
  { g: 'ἐγείρω', e: 'I raise up, wake', pos: 'verb', freq: 144 },
  { g: 'ἀγαπάω', e: 'I love, cherish', pos: 'verb', freq: 143 },
  { g: 'προφήτης, -ου, ὁ', e: 'prophet', pos: 'noun', freq: 144 },
  { g: 'ἀγάπη, -ης, ἡ', e: 'love', pos: 'noun', freq: 116 },
  { g: 'ἀποθνῄσκω', e: 'I die, am about to die', pos: 'verb', freq: 111 },
  { g: 'ζωή, -ῆς, ἡ', e: 'life', pos: 'noun', freq: 135 },
  { g: 'ἀποστέλλω', e: 'I send (with a commission)', pos: 'verb', freq: 132 },
  { g: 'βλέπω', e: 'I see, look at', pos: 'verb', freq: 133 },
  { g: 'μένω', e: 'I remain, abide', pos: 'verb', freq: 118 },
  { g: 'σῴζω', e: 'I save, deliver, heal', pos: 'verb', freq: 106 },
  { g: 'ζάω', e: 'I live', pos: 'verb', freq: 140 },
  { g: 'βάλλω', e: 'I throw, put', pos: 'verb', freq: 122 },
  { g: 'διδάσκω', e: 'I teach', pos: 'verb', freq: 97 },
  { g: 'ὥρα, -ας, ἡ', e: 'hour, occasion, moment', pos: 'noun', freq: 106 },
  { g: 'γραφή, -ῆς, ἡ', e: 'writing, Scripture', pos: 'noun', freq: 50 },
  { g: 'εἰρήνη, -ης, ἡ', e: 'peace', pos: 'noun', freq: 92 },
  { g: 'χάρις, -ιτος, ἡ', e: 'grace, favour, kindness', pos: 'noun', freq: 155 },
  { g: 'ἀλήθεια, -ας, ἡ', e: 'truth', pos: 'noun', freq: 109 },
  { g: 'βασιλεύς, -έως, ὁ', e: 'king', pos: 'noun', freq: 115 },
  { g: 'αἰώνιος, -ον', e: 'eternal', pos: 'adjective', freq: 71 },
  { g: 'δικαιοσύνη, -ης, ἡ', e: 'righteousness, justice', pos: 'noun', freq: 92 },
  { g: 'κρίνω', e: 'I judge, decide', pos: 'verb', freq: 114 },
  { g: 'φῶς, φωτός, τό', e: 'light', pos: 'noun', freq: 73 },
  { g: 'θάνατος, -ου, ὁ', e: 'death', pos: 'noun', freq: 120 },
  { g: 'πληρόω', e: 'I fill, fulfil, complete', pos: 'verb', freq: 86 },
  { g: 'αἴρω', e: 'I take up, take away', pos: 'verb', freq: 101 },
  { g: 'δοῦλος, -ου, ὁ', e: 'slave, servant', pos: 'noun', freq: 124 },
  { g: 'ἀγαθός, -ή, -όν', e: 'good, useful', pos: 'adjective', freq: 102 },
  { g: 'βαπτίζω', e: 'I baptise, immerse', pos: 'verb', freq: 77 },
  { g: 'χαρά, -ᾶς, ἡ', e: 'joy, delight', pos: 'noun', freq: 59 },
  { g: 'ἐλπίς, -ίδος, ἡ', e: 'hope, expectation', pos: 'noun', freq: 53 },
  { g: 'σῶμα, -ατος, τό', e: 'body', pos: 'noun', freq: 142 },
  { g: 'ὁδός, -οῦ, ἡ', e: 'way, road, journey', pos: 'noun', freq: 101 },
  { g: 'καιρός, -οῦ, ὁ', e: 'time, appointed season', pos: 'noun', freq: 85 },
  { g: 'εὐαγγέλιον, -ου, τό', e: 'good news, gospel', pos: 'noun', freq: 76 }
];
